BEGIN;
    DROP VIEW IF EXISTS PROJECT_ITEM;
    DROP VIEW IF EXISTS PROJECT_REPRESENTATION;
    DROP VIEW IF EXISTS USER_ITEM;
    DROP VIEW IF EXISTS ISSUE_ITEM;
    DROP VIEW IF EXISTS ISSUE_REPRESENTATION;
    DROP VIEW IF EXISTS COMMENT_REPRESENTATION;

    DROP TABLE IF EXISTS SESSION;
    DROP TABLE IF EXISTS ISSUE_LABEL;
    DROP TABLE IF EXISTS ISSUE_STATE;
    DROP TABLE IF EXISTS COMMENT;
    DROP TABLE IF EXISTS STATE_TRANSITION;
    DROP TABLE IF EXISTS ISSUE;
    DROP TABLE IF EXISTS LABEL;
    DROP TABLE IF EXISTS STATE;
    DROP TABLE IF EXISTS PROJECT;
    DROP TABLE IF EXISTS "USER";
COMMIT;