BEGIN;
    DELETE FROM ISSUE_LABEL;
    DELETE FROM COMMENT;
    DELETE FROM STATE_TRANSITION;
    DELETE FROM ISSUE;
    DELETE FROM LABEL;
    DELETE FROM STATE;
    DELETE FROM PROJECT;
    DELETE FROM "USER";

    ALTER SEQUENCE comment_id_seq RESTART;
    ALTER SEQUENCE issue_id_seq RESTART;
    ALTER SEQUENCE label_id_seq RESTART;
    ALTER SEQUENCE project_id_seq RESTART;
    ALTER SEQUENCE state_id_seq RESTART;
COMMIT;